version: "3.7"

services:
  database_mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: crontabDB
    ports:
      - "3307:3306"
    volumes:
      - todo-mysql-data:/var/lib/mysql
    networks:
      - my_network
  
  cron_service:
    image: ubuntu_cron:2.0
    container_name: cron_container
    networks:
      - my_network
    depends_on:
      - database_mysql

networks:
  my_network:

volumes:
  todo-mysql-data: